version: '2'
services:
  app-lb:
    image: rancher/lb-service-haproxy:v0.7.5
    tty: true
    ports:
    - 7080:7080/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin
      io.rancher.container.create_agent: 'true'
  owncloud:
    image: owncloud
    links:
    - db:db
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password