version: '2'
services:
  app-lb:
    ports:
    - ${http_port}:9001/tcp
    labels:
      io.rancher.loadbalancer.target.owncloud: ${onwcloud_hostname}:9001=80
    tty: true
    image: rancher/lb-service-haproxy:v0.7.5
    links:
    - owncloud:owncloud
    - db:db
      stdin_open: true
  owncloud:
    labels:
      io.rancher.container.pull_image: always
    tty: true
    image: owncloud
    links:
    - db:db
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
 