version: '3.1'
services:
  app-lb:
    ports:
    - ${http_port}:${http_port}/tcp
    labels:
      io.rancher.loadbalancer.target.owncloud: ${onwcloud_hostname}:${http_port}=80
    tty: true
    image: rancher/lb-service-haproxy:v0.7.5
    links:
    - owncloud:owncloud
          stdin_open: true
  owncloud:
    labels:
      io.rancher.container.pull_image: always
    tty: true
    image: owncloud
    links:
    - db:db
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
 