version: '2'
catalog:
  name: Owncloud
  version: 0.0.1-rancher1
  description: |
    Gerenciados de Arquivos
  minimum_rancher_version: v0.56.0
  maintainer: "Luiz Henrique <luiz@madeiracampos.com>"
  uuid: owncloud
services:
  app-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - protocol: http
        service: owncloud
        source_port: 7080
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
  owncloud:
    scale: 1
    start_on_create: true
  db:
    scale: 1
    start_on_create: true