version: '2'
catalog:
  name: Owncloud
  version: v0.1-owncloud
  description: |
    Gerenciados de Arquivos
  minimum_rancher_version: v0.56.0
  maintainer: "Luiz Henrique <luiz@madeiracampos.com>"
  uuid: owncloud-0
  questions:
    - variable: "http_port"
      description: "Porta HTTP que será exposta:"
      label: "Porta HTTP:"
      required: true
      default: 8080
      type: "int"
 
  owncloud:
    scale: 1
    start_on_create: true
  db:
    scale: 1
    start_on_create: true
    
   