version: '2'
services:
  app-lb:
    ports:
    - ${http_port}:${http_port}/tcp
    labels:
      io.rancher.loadbalancer.target.owncloud: ${dokuwiki_hostname}:${http_port}=80
    tty: true
    image: rancher/load-balancer-service
    links:
    - dokuwiki:dokuwiki
    stdin_open: true
  dokuwiki:
      image: bitnami/dokuwiki:latest
      tty: true
        