version: '2'
services:
  dokuwiki:
    image: 'bitnami/dokuwiki:latest'
    labels:
      kompose.service.type: nodeport
    ports:
    - ${http_port}:9002/tcp
    volumes:
      - 'dokuwiki_data:/bitnami'
volumes:
  dokuwiki_data:
    driver: local
