version: '2'
catalog:
  name: Dokuwiki
  version: v0.1-Dokuwiki
  description: |
    Dokuwiki
  minimum_rancher_version: v0.56.0
  maintainer: "Luiz Henrique <luiz@madeiracampos.com>"
  uuid: Dokuwiki-0
  questions:
    - variable: "http_port"
      description: "Porta HTTP que será exposta:"
      label: "Porta HTTP:"
      required: true
      default: 8080
      type: "int"
      options:
        - local
      
services:
  app-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - protocol: http
        service: dokuwiki
        source_port: 7080
        target_port: 80
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate 
  owncloud:
    scale: 1
    start_on_create: true
  db:
    scale: 1
    start_on_create: true
 