---
name: Redmine
description: >
  Software para Gerenciar Projetos.
version: 0.0.1-rancher1-redmine
category: Repositório
maintainer: Luiz Henrique <luiz@madeiracampos.com>
license: GNU GPL v3
projectURL: https://github.com/luiz-madeira/catalogs-rancher
