version: '2'
catalog:
  name: Redmine
  version: v0.1-redmine
  description: |
    Softtware de Gerenciamento de projeto.
  minimum_rancher_version: v0.56.0
  maintainer: "Luiz Henrique <luiz@madeiracampos.com>"
  uuid: redmine-0
  questions:
    - variable: db_password
      description: "Senha para o banco de dados"
      label: "Password (default: redmine)"
      required: true
      default: "redmine"
      type: "password"
    - variable: "redmine_hostname"
      description: "Redmine hostname"
      label: "Hostname:"
      required: true
      default: "redmine"
      type: "string"
    - variable: "http_port"
      description: "HTTP port to expose on host. Will be used to bind TCP"
      label: "HTTP port:"
      required: true
      default: 80
      type: "string"
   
      
services:
  app-lb:
      scale: 1
      load_balancer_config:
        haproxy_config: {}
      health_check:
        port: 42
        interval: 2000
        unhealthy_threshold: 3
        strategy: recreate
        response_timeout: 2000
        healthy_threshold: 2

  redmine:
    scale: 1
    start_on_create: true
  db:
    scale: 1
    start_on_create: true
    
   