version: '2'
services:
  app-lb:
    ports:
    - ${http_port}:${http_port}/tcp
    labels:
      io.rancher.loadbalancer.target.joomla: ${joomla_hostname}:${http_port}=80
    tty: true
    image: rancher/load-balancer-service
    links:
    - joomla:joomla
    stdin_open: true
  joomla:
    image: joomla
    links:
      - joomladb:mysql
    ports:
      - 8181:80    
    environment:
      JOOMLA_DB_HOST: ${joomla_dbhostname}
      JOOMLA_DB_PASSWORD: ${db_password}
 
  joomladb:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: ${db_password}
 